### ISSUE TITLE
russian version

### ISSUE THREAD

**Issue by smilik3** [davghouse/Daves.WordamentSolver#24]
hello can u help me with russian version, i have a dictionary ,but i idk what i need to do

**Comment by davghouse** [comment]
[Here's a gist](https://gist.github.com/davghouse/1751dec3c73ebfdc730ae4b5ab6dae6f) demonstrating how you'd do this without making code changes, just using the existing extensibility points. You can put that method in SolutionTests.cs and experiment a bit.

I don't know anything about Russian Wordament or the Russian language though. It could be the case that your Wordament has different tile types, or that your language differentiates between upper and lower case letters in some significant way, or that Russian Wordament has different rules for calculating tile points of special tile types, or different special tile types altogether.

If you're going to make your fork Russian-centric, you'd want to replace Dictionary.txt with a Russian dictionary, and replace Board's BasicTileValues with whatever the Russian basic tile values are. Then check out the current tile types and see if they're covering everything that Russian Wordament uses, and if the GuessPoints methods seem reasonable.

And one thing to note, you need to be really careful to use the correct letters across your Dictionary, your BasicTileValues, and the boards that you submit to the solver. 'A' and 'А' look the same on my screen but are different (try googling them).

Good luck!

**Comment by smilik3** [comment]
thank you very much
